### ISSUE TITLE
weird interation with inspiration's changes to the vanilla cauldron

### ISSUE THREAD

**Issue by majijn** [Lemonszz/Fluid-Funnel#7]
it's not checking how much space for fluid there is, (I have it set in the config so the cauldron can hold 4 water bottles worth of water, at 250mb each) but the funnel only inputs up to 3 bottles, and also it doesnt actually check what fluid it's going to transfer into the cauldron. it's changing for example liquid starlight into water. 1bucket into 250mb of water

**Comment by Lemonszz** [comment]
If I recall correctly, the Fluid Funnel's cauldron interaction is incompatible with Inspiration's changes. Setting  "fillCauldron" to false in Fluid Funnel's config should fix the issue.

If the funnel doesn't interact with the inspiriation's cauldron with fillCauldron set to false, that's a bug.

**Comment by majijn** [comment]
it doesnt interact with it at all if the config is set to false, also I forgot to mention the tap doesnt interact with it at all either, but given yours isnt the only mod that is having trouble interacting with the cauldron ive posted up an issue on their end

**Comment by Lemonszz** [comment]
👍 I'll keep this issue open then.

**Comment by majijn** [comment]
so it turns out it used to work because in a previous pack funnels were set to move fluids in 250mb increments, which I hadnt done in my kitchensink pack, that's what was causing the issue
